### ISSUE TITLE
Graphical Bugs

### ISSUE THREAD

**Issue by thegreatrazz** [mathsnz/NZGrapher#10]
We were using NZGrapher in Mathematics and my friend has experienced a graphical bug shown in the attached screenshot.

The graph can be copied into the text input field.

![screenshot 23](https://cloud.githubusercontent.com/assets/7696711/24224966/f0ad40fc-0fc2-11e7-9f5b-a50bc9220001.png)

**Comment by mathsnz** [comment]
Thanks, I've updated the code so you can no longer paste images onto the page.
