### ISSUE TITLE
No LICENSE file?

### ISSUE THREAD

**Issue by sticks-stuff** [mathsnz/NZGrapher#13]
What license is NZGrapher under?

**Comment by mathsnz** [comment]
NZGrapher doesn't have a licence per-say.
I've provided the source code for students to be able to look at it for those that are curious, but it's not under any licence for people to be able to re-use.

**Comment by DrMeepso** [comment]
So it's source available, not open source?

**Comment by mathsnz** [comment]
That is correct.
